name: CI
on: [push]
jobs:
  build:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1.1
      with:
        mono-version: latest
        xamarin-ios-version: latest
        xamarin-android-version: latest
        xcode-version: latest
